// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRDH_API.Data;

#nullable disable

namespace PRDH_API.Domain.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230930053005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("PRDH.Entities.Case", b =>
                {
                    b.Property<Guid>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarliestPositiveOrderTestSampleCollectedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarliestPositiveOrderTestType")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderTestCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.HasKey("CaseId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("PRDH.Entities.LaboratoryTest", b =>
                {
                    b.Property<Guid>("OrderTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTestResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTestType")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SampleCollectedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderTestId");

                    b.ToTable("LaboratoryTests");
                });
#pragma warning restore 612, 618
        }
    }
}
